
import React, { useRef, useEffect } from 'react';
import { AlertTriangle } from 'lucide-react';

const Disclaimer: React.FC = () => {
  const disclaimerRef = useRef<HTMLDivElement>(null);
  
  useEffect(() => {
    // Check if element is in viewport
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach(entry => {
          if (entry.isIntersecting) {
            entry.target.classList.add('is-visible');
          }
        });
      },
      { threshold: 0.1 }
    );
    
    if (disclaimerRef.current) {
      observer.observe(disclaimerRef.current);
    }
    
    return () => {
      if (disclaimerRef.current) {
        observer.unobserve(disclaimerRef.current);
      }
    };
  }, []);

  return (
    <section id="disclaimer" className="section relative">
      {/* Background Elements */}
      <div className="absolute inset-0 cyberpunk-grid -z-10 opacity-30"></div>
      
      <div className="container mx-auto px-4">
        <div className="max-w-4xl mx-auto">
          <div className="flex items-center justify-center mb-8 fade-in-section" ref={disclaimerRef}>
            <div className="w-14 h-14 flex items-center justify-center rounded-full bg-destructive/10 border border-destructive/30 mr-4">
              <AlertTriangle className="w-7 h-7 text-destructive" />
            </div>
            <h2 className="text-3xl md:text-4xl font-bold">Legal Disclaimer</h2>
          </div>
          
          <div className="glass-card p-8 fade-in-section">
            <div className="space-y-4 text-white/80">
              <p>
                <strong className="text-white">Informational Purposes Only:</strong> Materiumor - The Material Valuation GPT ("Materiumor") is provided for informational and educational purposes only. The valuations, grading, and assessments generated by Materiumor are not intended to constitute professional advice or serve as a substitute for professional appraisal services.
              </p>
              
              <p>
                <strong className="text-white">No Guarantee of Accuracy:</strong> While we strive to provide accurate and up-to-date information, AI Web Tools LLC makes no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability or availability of Materiumor or the information it generates. Market conditions for materials, precious metals, gemstones, and digital currencies are subject to rapid fluctuations.
              </p>
              
              <p>
                <strong className="text-white">Not Financial Advice:</strong> Information provided by Materiumor does not constitute financial, investment, legal, or tax advice. Users should consult with qualified professionals before making any financial decisions based on valuations provided by Materiumor.
              </p>
              
              <p>
                <strong className="text-white">Third-Party Verification:</strong> For significant financial transactions, insurance purposes, or legal matters, users are strongly encouraged to seek independent verification from certified appraisers, gemologists, assayers, or other appropriate professionals.
              </p>
              
              <p>
                <strong className="text-white">Limitation of Liability:</strong> In no event shall AI Web Tools LLC, its affiliates, or service providers be liable for any direct, indirect, incidental, special, or consequential damages arising out of or in any way connected with the use of Materiumor, whether based on warranty, contract, tort, or any other legal theory, even if advised of the possibility of such damages.
              </p>
              
              <p>
                <strong className="text-white">External Links:</strong> Materiumor may provide links to external websites or resources. These links are provided for convenience only; AI Web Tools LLC has no control over and assumes no responsibility for the content, privacy policies, or practices of any third-party websites or resources.
              </p>
              
              <p>
                <strong className="text-white">Changes to Service:</strong> AI Web Tools LLC reserves the right to modify, suspend, or discontinue Materiumor or any part thereof, temporarily or permanently, with or without notice.
              </p>
              
              <p>
                <strong className="text-white">Governing Law:</strong> This disclaimer shall be governed by and construed in accordance with the laws of the jurisdiction in which AI Web Tools LLC is registered, without regard to its conflict of law provisions.
              </p>
              
              <p>
                By using Materiumor, you acknowledge that you have read, understood, and agree to be bound by this disclaimer.
              </p>
              
              <p className="text-sm">
                Last updated: May 2024
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Disclaimer;
